### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by zhenglaizhang** [zhenglaizhang/wired-brain-coffee#3]
- [ ] issue template
- [ ] pull request template
- [ ] go to probot.github.io and explore more apps, e.g close-issue-app
- [ ] try create folder from github ui
- [ ] check all configurations of a github repo
- [ ] design a app to use github app note taking app
- [ ] github app to auto delete a merged branch
